config/routes.rb
Rails.application.routes.draw do

  root 'session#index'

    resources :user
  get '/session/index' => 'session#index'
  post '/session/login' => 'session#login'
  get '/session/logout' => 'session#logout', :as => 'logout'

  resources :admin
  post '/dashboard/admin_login' => 'dashboard#admin_login'
  get '/dashboard/admin_logout' => 'dashboard#admin_logout'
  get '/dashboard/admin_view/:book_id' => 'dashboard#admin_book_view', :as => 'admin_book_view'
  patch '/dashboard/admin_update/:book_id' => 'dashboard#admin_book_update', :as => 'admin_book_update'
  get '/dashboard/admin_add_book' => 'dashboard#admin#admin_add_book', :as => 'admin_add_book'
  post 'dashboard/create' => 'dashboard#create', :as => 'create_book'
  get 'dashboard/admin_book/:checkout_id' => 'dashboard#admin_book', :as => 'view_checkedout_book'
  get 'dashboard/view_all' => 'dashboard#view_all', :as => 'view_all'
  

  resources :checkout
  post '/checkout/new_checkout' => 'checkout#new_checkout'

  resources :books
  resources :checkin
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def admin
    @book = Book.new
  end

  def admin_add_book
    @book = Book.new(book_params)
    if @book.save
      respond_to do |format|
        format.html {redirect_to admin_index_path}
        format.json {render :json => @book}
      end
    else
      flash[:notice] = "Creation unsuccessful, please try again"
      redirect_to admin_add_book
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      respond_to do |format|
        format.html {redirect_to admin_index_path}
        format.json {render :json => @book}
      end
    else
      flash[:notice] = "Creation unsuccessful, please try again"
      redirect_to admin_add_book
    end
  end


  def admin_login
    @admin = get_admin(params[:admin])
    if @admin && @admin.authenticate(params[:admin][:password])
      session[:admin_id] = @admin.id
      redirect_to admin_path(@admin.id)
    else
      flash[:notice] = "Invalid username or password"
      redirect_to root_path
    end
  end

  def admin_logout
    session.clear
    flash[:notice] = "See you next time."
    redirect_to root_path
  end

  def admin_book_view
    @book = Book.find(params[:book_id])
  end

  def admin_book_update
    @book = Book.find(params[:book_id])
    @book.update(params[:book])

    redirect_to admin_path(Admin.find(session[:admin_id]))
  end

  def admin_book
    @checkout = Checkout.find(params[:checkout_id])
    book = @checkout.book_id
    user = @checkout.user_id
    @book = Book.find(book)
    @user = User.find(user)
  end

  def view_all
    @books = Book.all
  end


                          

  protected

  def get_admin(admin_params)
    Admin.find_by(email: admin_params[:email])
  end

  def book_params
    params.require(:book).permit(:title, :author, :genre)
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper

	def sortable(column, title = nil)
  	title ||= column.titleize
  	css_class = column == sort_column ? "current #{sort_direction}" : nil
  	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  	link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end

end

app/views/dashboard/_edit.html.erb
<div class="admin_update">
  <table summary="Book Form Fields">
    <tr>
     <th><%= f.label(:title,"Title") %></th>
     <td><%= f.text_field(:title) %></td>
    </tr>
    <tr>
     <th><%= f.label(:author, "Author") %></th>
     <td><%= f.text_field(:author) %></td>
    </tr>
    <tr>
     <th><%= f.label(:genre, "Genre") %></th>
     <td><%= f.text_field(:genre) %></td>
    </tr>
    <tr>
     <th><%= f.label(:good_reads_id, "Good Reads Id") %></th>
     <td><%= f.text_field(:good_reads_id) %></td>
    </tr>
   </table>
</div>
<div class="update-button">
    <class="cta-button"><a class="button"><%= submit_tag("Update Book!") %> </a>
</div>    

app/views/dashboard/admin.html.erb
<div class="newBook">
  <div class="small-3 columns" name="new" id="book">
  <%= form_for @book, :url => url_for(:controller => 'dashboard', :action => 'create') do |f| %>
    <p>
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </p>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :genre %><br>
      <%= f.text_field :genre %>
    </p>

    <p>
      <%= f.label :good_reads_id %><br>
      <%= f.text_field :good_reads_id %>
    </p>
   
    <p>
      <button class = "button">Create</button>
    </p>
  <% end %>
  </div>
</div>  

<div class="backnew">
<%= link_to 'Back', admin_index_path %>
</div>

app/views/dashboard/admin_book.html.erb
<div class="backnew">
<%= link_to 'Back', admin_index_path %>
</div>

<div class="xhr_book_info" >
	<p><%= @book.title %> is currently checkedout by <%= @user.username %> It's due to be returned on <%= @checkout.due_date %></p> 
	<a href="#" class="button tiny" id="close">Close</a>
</div>

app/views/dashboard/admin_book_view.html.erb
<%= link_to 'Home', admin_index_path %>


<%= form_for(@book, :url => {:action => 'admin_book_update', :id => @book.id}) do |f| %>
	<%= render(:partial => "edit", :locals => {:f => f}) %>  
<% end %>

app/views/dashboard/view_all.html.erb
<% @books.each do |book| %>
<div class="book">
	<ul class="pricing-table">
		<li class="title"> <%=book.title %>    </li>
		<li class="price"> <%=book.author %>   </li>
		<li class="description"> <%=book.genre %>  </li>
		<li class="bullet-item"> <p>Checkout status:</p> <%= book.checked_out? %>    </li>
		<li class="cta-button"><a class="button" <%= link_to 'Book Details', admin_book_view_path(book) %> </a></li>
	</ul>
</div>
<%end%>