config/routes.rb
Rails.application.routes.draw do

  root 'session#index'

    resources :user
  get '/session/index' => 'session#index'
  post '/session/login' => 'session#login'
  get '/session/logout' => 'session#logout', :as => 'logout'

  resources :admin
  post '/dashboard/admin_login' => 'dashboard#admin_login'
  get '/dashboard/admin_logout' => 'dashboard#admin_logout'
  get '/dashboard/admin_view/:book_id' => 'dashboard#admin_book_view', :as => 'admin_book_view'
  patch '/dashboard/admin_update/:book_id' => 'dashboard#admin_book_update', :as => 'admin_book_update'
  get '/dashboard/admin_add_book' => 'dashboard#admin#admin_add_book', :as => 'admin_add_book'
  post 'dashboard/create' => 'dashboard#create', :as => 'create_book'
  get 'dashboard/admin_book/:checkout_id' => 'dashboard#admin_book', :as => 'view_checkedout_book'
  get 'dashboard/view_all' => 'dashboard#view_all', :as => 'view_all'
  

  resources :checkout
  post '/checkout/new_checkout' => 'checkout#new_checkout'

  resources :books
  resources :checkin
end

app/views/admin/_current_checkouts.html.erb
<div class="admin_dropdown">
    <a href="#" class="button success" data-options="align:right" data-dropdown="drop">Current Checkouts &raquo;</a>
      <ul id="drop" class="large f-dropdown" data-dropdown-content>
        <% if @current_checkouts.length == 0 %>
          <li>There are no books checkedout</li>
        <%else%>
          <% @current_checkouts.each do |checkout| %>
            <li id="checkout_id"><%= link_to 'View Details', view_checkedout_book_path(checkout.id), :"data-href" => checkout.id %><strong><%= checkout.title %></strong></li>
          <%end%>
        <%end%>  
      </ul>
</div> 

app/views/admin/index.html.erb
    <div class = "sign-in">
        <%= form_for(:admin, :url => {:controller => 'dashboard', :action => 'admin_login'}) do |f|%>
            <%= f.email_field :email, :size => 70, placeholder: 'Email' %>
            <%= f.password_field :password, :size => 70, placeholder: 'Password' %>
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: name %>
            <% end %>
          <button type="submit" class="button button-block"/>Admin Login</button>
        <% end %>
    </div>

app/views/admin/show.html.erb
<p>Hello, <%=admin_user.email %></p>

<div class="addBook">
	<button class="button button-block round" /><%= link_to "Add a new book!", admin_add_book_path %></button>
</div>	


<%= render partial: "current_checkouts" %>

<div class="books_status">
	<p> There are currently <%= @current_checkouts.length %> book(s) checked out. </p>
</div>



<div class="books_number">
	<p> You have <%= @books %> books in your library. </p>
</div>


<div class="book_info">
	<p> <%= link_to "View all books", view_all_path %> </p>
</div>