config/routes.rb
Rails.application.routes.draw do

  root 'session#index'

    resources :user
  get '/session/index' => 'session#index'
  post '/session/login' => 'session#login'
  get '/session/logout' => 'session#logout', :as => 'logout'

  resources :admin
  post '/dashboard/admin_login' => 'dashboard#admin_login'
  get '/dashboard/admin_logout' => 'dashboard#admin_logout'
  get '/dashboard/admin_view/:book_id' => 'dashboard#admin_book_view', :as => 'admin_book_view'
  patch '/dashboard/admin_update/:book_id' => 'dashboard#admin_book_update', :as => 'admin_book_update'
  get '/dashboard/admin_add_book' => 'dashboard#admin#admin_add_book', :as => 'admin_add_book'
  post 'dashboard/create' => 'dashboard#create', :as => 'create_book'
  get 'dashboard/admin_book/:checkout_id' => 'dashboard#admin_book', :as => 'view_checkedout_book'
  get 'dashboard/view_all' => 'dashboard#view_all', :as => 'view_all'
  

  resources :checkout
  post '/checkout/new_checkout' => 'checkout#new_checkout'

  resources :books
  resources :checkin
end

app/models/book.rb
class Book < ActiveRecord::Base

  attr_accessible :title, :author, :genre, :good_reads_id, :checked_out?

  has_many :checkouts
  has_many :checkins
  has_many :users



  def self.search(search)
    if search
      where('title || author || genre LIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = User.find(session[:user_id])

    if params[:search]
      @user_search = Book.search(params[:search])
    else
      @books = Book.search(params[:search]).paginate(:page => params[:page], :per_page => 20)
    end
    
    @user_checkouts = @user.checkouts
  end

  def show
    @user = User.find(session[:user_id])
    @book = Book.find(params[:id])
    @book_checkouts = @book.checkouts.length
    @book_id = @book.good_reads_id
    @user_checkouts = @user.books.where(id: @book.id, checked_out?: true).limit(1)
  end



  private

  def book_params
    params.require(:book).permit(:title, :author, :genre,:checked_out?)
  end
end

app/helpers/book_helper.rb
module BookHelper

  def start_date
    t = Time.now
    checkout_date = t.strftime('%A %B %d %Y')
    return "Checkout date is: " + checkout_date
  end

  def due_date
    t = (Time.now + 60.days)
    checkin_date = t.strftime('%A %B %d %Y')
    return "The due date is: " + checkin_date
  end


  def show_dates
    if @book.checked_out? == true
      if @user_checkouts.length > 0
        return due_date
      else
        return "This book is currently checked out"
      end
    else
      return start_date + " " + due_date
    end
  end



  def good_reads_data(book)
    client = Goodreads.new(api_key: 'dLe4w6mTCE44oYBGPDNg')
    @search = client.book(book)

    rating
    formatted_string
  end

  def formatted_string
    edit = @search.description.gsub(/(&amp)/, '')
    return edit
  end

  def rating
    return  @search.average_rating
  end

end

app/views/books/_book.html.erb
<div class="book">
	<ul class="pricing-table">
		<li class="title"> <%=book.title %>    </li>
		<li class="price"> <%=book.author %>   </li>
		<li class="description"> <%=book.genre %>  </li>
		<li class="bullet-item"> <p>Checkout status:</p> <%= book.checked_out? %>    </li>
		<li class="cta-button"><a class="button" <%= link_to 'Book Details', book_path(book) %> </a></li>
	</ul>
</div>

app/views/books/_checkouts.html.erb
<div class="dropdown">
    <a href="#" class="button success" data-options="align:right" data-dropdown="drop">Books &raquo;</a>
      <ul id="drop" class="large f-dropdown" data-dropdown-content>
        <% if @user_checkouts.length == 0 %>
          <li>You have no books currently checked out</li>
        <%else%>
          <% @user_checkouts.each do |checkout| %>
            <li><%= link_to 'View Details', book_path(checkout.id) %><strong><%= checkout.title %></strong></li>
          <%end%>
        <%end%>  
      </ul>
</div>

app/views/books/_show_dates.html.erb
<% if @book.checked_out? == true %>
	<%  @book_checkouts.each do |checkout| %>
		<%  if (checkout.user_id == @user.id && checkout.book_id == @book.id) %>
   			<% return "Your due date is: " + checkout.due_date.to_s %>
		<%  else  %> 
   			<% return "This book is currently checked out" %>
		<%  end %>
	<% end %>
<% else %> 
	<% return start_date + " " +  due_date %>
<% end %>

app/views/books/index.html.erb
<div id="header-wrap">
  <li>Hello, <%=current_user.username%></li>
</div>

<%= form_tag books_path, method: "get" do %>
  <%= text_field_tag :search, params[:search], :autofocus => true, :placeholder => "Search by Title, Author, Genre", :id => "bookSearch" %>
<% end %>

<div id="books">
  <% if @user_search %>
  	<%= render @user_search %>
  <%else%>
  	<%= will_paginate @books %>
  <%end%>
</div>

<div class="dropdown">
  <a data-dropdown="drop1" class="button success" aria-controls="drop1" aria-expanded="false">Your Books</a>
  <ul id="drop1" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
     <% @user_checkouts.each do |checkout| %>
            <li><%= link_to '', book_path(checkout.book) %><strong><%= checkout.book.title %></strong>--Details</li>
         <%end%>
  </ul>
</div>

app/views/books/show.html.erb
<div id="header-wrap">
  <li>Hello, <%=current_user.username%></li>
</div>


<div class ="book_details">
  <p>Title:</p> <h5>  <%= @book.title  %> </h5>
  <p>Author:</p> <h5> <%= @book.author %> </h5>
  <p>Genre:</p> <h5>  <%= @book.genre  %> </h5>
  <p>Info: </p>  <h3> <%= show_dates   %> </h3>
  <p> This book has been checked out:</p> <h4> <%=@book_checkouts %> time(s) </h4>
</div>



<div class="span_holder">
  <span class="purple">Synopsis:</span>
</div>  




<div class="good_reads">
  <% good_reads_data(@book_id) %>
  <p> <%= strip_tags(formatted_string) %> </p> <br>
  <div class="checkout_button">
  <% if @book.checked_out? == true %>
      <% if @user_checkouts.length > 0 %>
        <button class="button button-block" /><a class="button" <%= link_to "Checkin",checkin_path(@book) %></button>
      <%else %>
        <button class="button button-block"  disabled />This book is currently checked out</button>
      <%end%> 
  <%else%>
    <button class="button button-block"><a class="button" <%= link_to 'Checkout', checkout_path(@book) %></button>
  <%end%>
  </div>  
</div>

<div class="ratings">
  <span class="blue">Good Reads Rating: </span><span class="orange"> <%= rating %> </span>
</div>